#ifndef BADEFINES_H
#define BADEFINES_H

#include <QObject>

const quint8 MAX_GOOD_NAME_LENGTH = 16;
const quint8 MAX_CUSTOMER_NAME_LENGTH = 16;
const quint8 MAX_COMPANY_NAME_LENGTH = 16;
const quint8 MAX_TRADER_NAME_LENGTH = 16;
const quint8 MAX_TRADER_SECOND_NAME_LENGTH = 16;

const quint8 MAX_GOOD_CATEGORY_NAME_LENGTH = 16;
const quint8 MAX_CUSTOMER_REGION_NAME_LENGTH = 16;

const quint8 MAX_FLOAT_NUMBER_LENGTH = 8;
const quint8 MAX_DISCOUNT_NUMBER_LENGTH = 3;
const quint8 MAX_INVOICE_ID_LENGTH = 10;

const quint8 MAX_INVOICE_ITEMS = 40;
const quint32 MAX_INVOICE_ID_VALUE = 1000000000;

#endif // BADEFINES_H
